version: "3.7"

services:
  client:
    container_name: "snailycad-client"
    restart: on-failure
    image: node:14
    command: sh -c "cd client && npm install && npm run build && npm run serve"
    ports:
      - "80:80"
    env_file: ./.env
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}

    working_dir: /cad
    volumes:
      - ./:/cad
    networks:
      - "web"

  server:
    container_name: "snailycad-server"
    links:
      - db:db
    restart: on-failure
    image: node:14
    command: sh -c "cd server && npm install && npm start"
    depends_on:
      - db
    ports:
      - "3030:3030"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      PORT: ${PORT}
      ENVIRONMENT: ${ENVIRONMENT}
    networks:
      - web

    working_dir: /cad
    volumes:
      - ./:/cad

  db:
    container_name: snailycad-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_PATH_HOST: /tmp/mysql
    restart: on-failure
    volumes:
      - /tmp/mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

networks:
  web:
    external: true
