version: "3.7"

services:
  client:
    container_name: "snailycad-client"
    restart: on-failure
    image: node:14
    command: sh -c "cd client && npm install && npm run build && npm run serve"
    ports:
      - "5000:5000"

    working_dir: /cad
    volumes:
      - ./:/cad
    networks:
      - "web"

  server:
    links:
      - db:db
    container_name: "snailycad-server"
    restart: on-failure
    image: node:14
    command: sh -c "cd server && npm install && npm start"
    depends_on:
      - db
    ports:
      - "3030:3030"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web

    working_dir: /cad
    volumes:
      - ./:/cad

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_PATH_HOST: /tmp/mysql
    restart: on-failure
    volumes:
      - /tmp/mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    depends_on:
      - db
    links:
      - db:db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - web

networks:
  web:
    external: true
